export const types = Object.freeze({
    WORLDWIP_START_FETCHING: 'WORLDWIP_START_FETCHING',
    WORLDWIP_STOP_FETCHING: 'WORLDWIP_STOP_FETCHING',
    WORLDWIP_SET_FETCHING_ERROR: 'WORLDWIP_SET_FETCHING_ERROR',
    WORLDWIP_FILL_DATA: 'WORLDWIP_FILL_DATA',
    WORLDWIP_FILTER_DATA: 'WORLDWIP_FILTER_DATA',
    WORLDWIP_FETCH_ASYNC: 'WORLDWIP_FETCH_ASYNC',
});
