export const types = Object.freeze({
    COUNTRIES_START_FETCHING: 'COUNTRIES_START_FETCHING',
    COUNTRIES_STOP_FETCHING: 'COUNTRIES_STOP_FETCHING',
    COUNTRIES_SET_FETCHING_ERROR: 'COUNTRIES_SET_FETCHING_ERROR',
    COUNTRIES_FILL_DATA: 'COUNTRIES_FILL_DATA',
    COUNTRIES_FETCH_ASYNC: 'COUNTRIES_FETCH_ASYNC',
});
