export const types = Object.freeze({
    LIVEBYCOUNTRY_START_FETCHING: 'LIVEBYCOUNTRY_START_FETCHING',
    LIVEBYCOUNTRY_STOP_FETCHING: 'LIVEBYCOUNTRY_STOP_FETCHING',
    LIVEBYCOUNTRY_SET_FETCHING_ERROR: 'LIVEBYCOUNTRY_SET_FETCHING_ERROR',
    LIVEBYCOUNTRY_FILL_DATA: 'LIVEBYCOUNTRY_FILL_DATA',
    LIVEBYCOUNTRY_FILTER_DATA: 'LIVEBYCOUNTRY_FILTER_DATA',
    LIVEBYCOUNTRY_FETCH_ASYNC: 'LIVEBYCOUNTRY_FETCH_ASYNC',
});
